meta_product_name: "Stormy Crossing"
meta_title: "Stormy Crossing - The most realistic and immersive sailing experiences online"
meta_description: "Stormy Crossing it's a games that are both entertaining and educational, providing players with a truly authentic sailing experience with real time weather conditions"
meta_image: "meta_cover.png" # should exist in `app/assets/images/`
twitter_account: "@Lewagonparis"   # required for Twitter Cards
